<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_61ea7a87e8e9f',
    'title' => __('Recommendations', 'modularity-recommend'),
    'fields' => array(
        0 => array(
            'key' => 'field_61ea7a992b202',
            'label' => __('Add links', 'modularity-recommend'),
            'name' => '',
            'aria-label' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('This module enables you to add static quicklinks to enable recommended links.', 'modularity-recommend'),
            'new_lines' => 'wpautop',
            'esc_html' => 0,
        ),
        1 => array(
            'key' => 'field_61ea7ae22b203',
            'label' => __('Link list', 'modularity-recommend'),
            'name' => 'recommend_link_list',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'acfe_repeater_stylised_button' => 0,
            'layout' => 'block',
            'pagination' => 0,
            'min' => 0,
            'max' => 20,
            'collapsed' => 'field_61ea7afd2b204',
            'button_label' => __('Add new recommendation', 'modularity-recommend'),
            'rows_per_page' => 20,
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_61ea7afd2b204',
                    'label' => __('Label', 'modularity-recommend'),
                    'name' => 'recommend_link_label',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'parent_repeater' => 'field_61ea7ae22b203',
                ),
                1 => array(
                    'key' => 'field_61ea7b1c2b205',
                    'label' => __('Target', 'modularity-recommend'),
                    'name' => 'recommend_link_target',
                    'aria-label' => '',
                    'type' => 'post_object',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_673b050aa3c4c',
                                'operator' => '!=',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '40',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => '',
                    'post_status' => '',
                    'taxonomy' => '',
                    'return_format' => 'id',
                    'multiple' => 0,
                    'save_custom' => 0,
                    'save_post_status' => 'publish',
                    'acfe_bidirectional' => array(
                        'acfe_bidirectional_enabled' => '0',
                    ),
                    'allow_null' => 0,
                    'bidirectional' => 0,
                    'ui' => 1,
                    'bidirectional_target' => array(
                    ),
                    'save_post_type' => '',
                    'parent_repeater' => 'field_61ea7ae22b203',
                ),
                2 => array(
                    'key' => 'field_673b052aa3c4d',
                    'label' => __('Target', 'modularity-recommend'),
                    'name' => 'recommend_link_target_external',
                    'aria-label' => '',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_673b050aa3c4c',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '40',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => __('https://', 'modularity-recommend'),
                    'parent_repeater' => 'field_61ea7ae22b203',
                ),
                3 => array(
                    'key' => 'field_673b050aa3c4c',
                    'label' => __('External link', 'modularity-recommend'),
                    'name' => 'recommend_link_is_external',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_628b9314f8dee',
                                'operator' => '==',
                                'value' => 'button',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '10',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => __('Yes', 'modularity-recommend'),
                    'default_value' => 0,
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                    'parent_repeater' => 'field_61ea7ae22b203',
                ),
            ),
        ),
        2 => array(
            'key' => 'field_628b9314f8dee',
            'label' => __('Display as', 'modularity-recommend'),
            'name' => 'template',
            'aria-label' => '',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'button' => __('Button', 'modularity-recommend'),
                'card' => __('Card', 'modularity-recommend'),
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'default_value' => __('button', 'modularity-recommend'),
            'layout' => 'horizontal',
            'return_format' => 'value',
            'save_other_choice' => 0,
        ),
        3 => array(
            'key' => 'field_629078026dc49',
            'label' => __('Columns', 'modularity-recommend'),
            'name' => 'recommend_columns',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_628b9314f8dee',
                        'operator' => '==',
                        'value' => 'card',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                1 => __('1', 'modularity-recommend'),
                2 => __('2', 'modularity-recommend'),
                3 => __('3', 'modularity-recommend'),
                4 => __('4', 'modularity-recommend'),
            ),
            'default_value' => false,
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'return_format' => 'value',
            'ajax' => 0,
            'placeholder' => '',
            'allow_custom' => 0,
            'search_placeholder' => '',
        ),
        4 => array(
            'key' => 'field_61eab66ec9a8b',
            'label' => __('Max number of autosuggested recommendations', 'modularity-recommend'),
            'name' => 'rekai_number_of_recommendation',
            'aria-label' => '',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 7,
            'placeholder' => __('items', 'modularity-recommend'),
            'prepend' => '',
            'append' => __('items', 'modularity-recommend'),
            'min' => 0,
            'max' => 10,
            'step' => 1,
        ),
        5 => array(
            'key' => 'field_628c958c693a9',
            'label' => __('RekAI', 'modularity-recommend'),
            'name' => 'rekai',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => __('Settings specific to RekAI.', 'modularity-recommend'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_628ca57c99f4b',
                    'label' => __('Filter from current page', 'modularity-recommend'),
                    'name' => 'userootpath',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => __('Automatically filter recommendations based on the current url.', 'modularity-recommend'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 1,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                ),
                1 => array(
                    'key' => 'field_628ca7e268d09',
                    'label' => __('Url level', 'modularity-recommend'),
                    'name' => 'rootpathlevel',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => __('Controls whether only pages below the current url path should be recommended from a certain level.', 'modularity-recommend'),
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_628ca57c99f4b',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                2 => array(
                    'key' => 'field_628c963a693aa',
                    'label' => __('Include pages', 'modularity-recommend'),
                    'name' => 'subtree',
                    'aria-label' => '',
                    'type' => 'post_object',
                    'instructions' => __('Controls whether only pages under a particular branch of the site should be displayed. Leave blank to include all pages.', 'modularity-recommend'),
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_628ca57c99f4b',
                                'operator' => '!=',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => '',
                    'taxonomy' => '',
                    'allow_null' => 0,
                    'multiple' => 1,
                    'return_format' => 'object',
                    'ui' => 1,
                    'bidirectional_target' => array(
                    ),
                    'save_custom' => 0,
                    'save_post_type' => '',
                    'save_post_status' => '',
                ),
                3 => array(
                    'key' => 'field_628c96c84e43c',
                    'label' => __('Exclude pages', 'modularity-recommend'),
                    'name' => 'excludetree',
                    'aria-label' => '',
                    'type' => 'post_object',
                    'instructions' => __('Controls whether certain pages should be excluded from viewing.', 'modularity-recommend'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => '',
                    'taxonomy' => '',
                    'allow_null' => 0,
                    'multiple' => 1,
                    'return_format' => 'object',
                    'ui' => 1,
                    'bidirectional_target' => array(
                    ),
                    'save_custom' => 0,
                    'save_post_type' => '',
                    'save_post_status' => '',
                ),
                4 => array(
                    'key' => 'field_628b4e43953e8',
                    'label' => __('Advanced options', 'modularity-recommend'),
                    'name' => 'advanced_options',
                    'aria-label' => '',
                    'type' => 'textarea',
                    'instructions' => __('Add custom options in valid JSON format.', 'modularity-recommend'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => __('{ "key": "value" }', 'modularity-recommend'),
                    'maxlength' => '',
                    'rows' => '',
                    'new_lines' => '',
                    'acfe_textarea_code' => 0,
                ),
            ),
            'acfe_seamless_style' => 0,
            'acfe_group_modal' => 0,
            'acfe_group_modal_close' => 0,
            'acfe_group_modal_button' => '',
            'acfe_group_modal_size' => 'large',
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-recommend',
            ),
        ),
        1 => array(
            0 => array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/recommend',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
));
}